version: "3"

services:
  mysql:
    image: postgres:12
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=bread
      - POSTGRES_USER=bread
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - bread

  redis:
    image: redis:6
    container_name: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - bread

networks:
  bread:
    labels:
      - bread