server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  expired:
    access: 86400000
    refresh: 604800000
