name: deploy

on:
  push:
    branches:
      - main
      - feature/ci # for test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 1. set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: 2. grant execute permission for gradlew
        run: chmod +x gradlew

      - name: 3. build with gradle
        run: ./gradlew clean build

      - name: 4. Docker Build, Tag, Container Registry Push
        id: image
        env:
          CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
          ECR_REPOSITORY: today-bread-server
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Dockerfile -t today-bread .
          docker tag today-bread-server:latest $CONTAINER_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $CONTAINER_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=full-name::$CONTAINER_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: 5. Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: 6. Checkout to Argo repository
        uses: actions/checkout@v3
        with:
          repository: daily-develop/today-bread-argocd
          token: ${{ secrets.ACTION_TOKEN }}

      - name: 7. Image Version Change
        run: kustomize edit set image ${{ steps.image.outputs.full-name }}

      - name: 8. Argo Repository Commit & Push
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "update image tag"
          git push -u origin main
